alias: Heating Control Based on Time and Temperature
description: >
  Controls the heaters (sofa and desk) based on room temperature and specified time ranges.
  Sets HVAC mode to 'heat' with a higher target temperature during defined periods and to 'idle' with a lower target temperature otherwise.
trigger:
  # Trigger when temperature falls below 22°C
  - platform: numeric_state
    entity_id: sensor.wz_temp_temperature
    below: 22
  # Trigger when temperature rises above 20°C
  - platform: numeric_state
    entity_id: sensor.wz_temp_temperature
    above: 20
  # Time-based triggers at the start and end of each high heating period
  - platform: time
    at:
      - '05:00:00'
      - '07:00:00'
      - '16:00:00'
      - '21:00:00'
condition: []
action:
  - choose:
      # Condition to activate high heating
      - conditions:
          # Temperature is below 22°C
          - condition: numeric_state
            entity_id: sensor.wz_temp_temperature
            below: 22
          # Current time is within one of the high heating ranges
          - condition: or
            conditions:
              - condition: time
                after: '05:00:00'
                before: '07:00:00'
              - condition: time
                after: '16:00:00'
                before: '21:00:00'
        sequence:
          # Set HVAC mode to 'heat' for both heaters
          - service: climate.set_hvac_mode
            target:
              entity_id:
                - climate.wz_heizung_sofa
                - climate.wz_heizung_schreibtisch
            data:
              hvac_mode: 'heat'
          # Set target temperature to 23°C for both heaters
          - service: climate.set_temperature
            target:
              entity_id:
                - climate.wz_heizung_sofa
                - climate.wz_heizung_schreibtisch
            data:
              temperature: 23
      # Condition to set heating to idle
      - conditions:
          # Either the current time is outside all high heating ranges
          # OR the temperature is above 20°C
          - condition: or
            conditions:
              # Time is not within any high heating period
              - condition: and
                conditions:
                  - condition: not
                    conditions:
                      - condition: time
                        after: '05:00:00'
                        before: '07:00:00'
                      - condition: time
                        after: '16:00:00'
                        before: '21:00:00'
              # Temperature is above 20°C
              - condition: numeric_state
                entity_id: sensor.wz_temp_temperature
                above: 20
        sequence:
          # Set target temperature to 20°C for both heaters
          - service: climate.set_temperature
            target:
              entity_id:
                - climate.wz_heizung_sofa
                - climate.wz_heizung_schreibtisch
            data:
              temperature: 20
          # Set HVAC mode to 'idle' for both heaters
          - service: climate.set_hvac_mode
            target:
              entity_id:
                - climate.wz_heizung_sofa
                - climate.wz_heizung_schreibtisch
            data:
              hvac_mode: 'idle'
    default: []
mode: single